# Generated by Django 3.2.8 on 2021-10-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminSignupForms',
            new_name='AdminForms',
        ),
    ]
