# Generated by Django 3.2.8 on 2021-10-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorName', models.CharField(max_length=200)),
                ('uDate', models.DateTimeField()),
            ],
        ),
    ]
