# Generated by Django 3.2.8 on 2021-10-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_addcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorId', models.CharField(max_length=200)),
                ('sectorName', models.CharField(max_length=200)),
                ('categoryId', models.CharField(max_length=200)),
                ('categoryName', models.CharField(max_length=200)),
                ('subCategoryName', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
