# Generated by Django 3.2.8 on 2021-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_addsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforms',
            name='userType',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
