# Generated by Django 3.2.8 on 2021-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userforms_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProductServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('sectorId', models.CharField(max_length=200)),
                ('categoryId', models.CharField(max_length=200)),
                ('subCatId', models.CharField(max_length=200)),
                ('imageUrl_1', models.ImageField(upload_to='static/productImages/')),
                ('imageUrl_2', models.ImageField(upload_to='static/productImages/')),
                ('productPrice', models.CharField(max_length=200)),
                ('productHighlights', models.CharField(max_length=200)),
                ('productDescription', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
