# Generated by Django 3.2.8 on 2021-10-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_addproductservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproductservices',
            name='userId',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addproductservices',
            name='categoryId',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addproductservices',
            name='sectorId',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addproductservices',
            name='subCatId',
            field=models.IntegerField(max_length=200),
        ),
    ]
