# Generated by Django 3.2.8 on 2021-10-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211017_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductservices',
            name='imageUrl_1',
            field=models.ImageField(upload_to='static/productimages'),
        ),
        migrations.AlterField(
            model_name='addproductservices',
            name='imageUrl_2',
            field=models.ImageField(upload_to='static/productimages'),
        ),
    ]
