# Generated by Django 3.2.8 on 2021-10-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211018_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductservices',
            name='imageUrl_1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='addproductservices',
            name='imageUrl_2',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
