# Generated by Django 3.2.8 on 2021-10-18 09:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211018_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductservices',
            name='imageUrl_1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to='productimages/'),
        ),
        migrations.AlterField(
            model_name='addproductservices',
            name='imageUrl_2',
            field=models.ImageField(upload_to='productimages/'),
        ),
    ]
