# Generated by Django 3.2.8 on 2021-10-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_addproductservices_imageurl_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductservices',
            name='imageUrl_1',
            field=models.ImageField(upload_to='productimages/'),
        ),
    ]
