# Generated by Django 3.2.8 on 2021-10-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211018_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('productId', models.CharField(max_length=200)),
                ('affliateCode', models.CharField(max_length=200)),
            ],
        ),
    ]
