# Generated by Django 3.2.8 on 2021-10-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211026_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcategory',
            name='sectorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addsectors'),
        ),
        migrations.AlterField(
            model_name='addproductservices',
            name='productDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addproductservices',
            name='productHighlights',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addsubcategory',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addcategory'),
        ),
        migrations.AlterField(
            model_name='addsubcategory',
            name='sectorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addsectors'),
        ),
    ]
