# Generated by Django 3.2.8 on 2021-10-31 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_addcategory_sectorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliatelink',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addproductservices'),
        ),
        migrations.AlterField(
            model_name='affliatelink',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userforms'),
        ),
    ]
